version: '3.8'
services:
  backend:
    build: ./backend
    container_name: rtmp-rtsp-converter
    ports:
      - "8000:8000"
    depends_on:
      - rtsp-server

  rtsp-server:
    image: aler9/rtsp-simple-server
    container_name: rtsp-server
    ports:
      - "8554:8554"
  rtmp-server:
    image: tiangolo/nginx-rtmp
    container_name: nginx-rtmp
    ports:
      - "1935:1935"
