version: '3.8'
services:
  nginx-rtmp:
    image: tiangolo/nginx-rtmp
    ports:
      - "1935:1935"
  rtsp-server:
    image: aler9/rtsp-simple-server
    ports:
      - "8554:8554"
  converter:
    build: ./converter
    volumes:
      - ./converter:/app
    depends_on:
      - nginx-rtmp
      - rtsp-server
    ports:
      - "8000:8000"