FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt ./

# 🔧 Установим ffmpeg внутрь контейнера
RUN apt-get update && apt-get install -y ffmpeg && \
    pip install --no-cache-dir -r requirements.txt

COPY main.py ./

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
